import React, { useEffect, useState } from "react";
import { useParams, Link } from "react-router-dom";
import axios from "axios";
import { CheckCircle, XCircle, Warning, ShieldCheck, FileArrowDown, FilePdf, Eye } from "@phosphor-icons/react";

const API = `${process.env.REACT_APP_BACKEND_URL}/api`;
const auth = () => ({ headers: { Authorization: `Bearer ${localStorage.getItem("ace_token")}` } });


export default function ExportVerificationPage() {
  const { reference } = useParams();
  const [state, setState] = useState({ loading: true, data: null, error: null });

  useEffect(() => {
    axios.get(`${API}/driver-exports/verify/${reference}`, auth())
      .then(res => setState({ loading: false, data: res.data, error: null }))
      .catch(err => setState({
        loading: false, data: null,
        error: err.response?.data?.detail || err.message || "Verification failed",
      }));
  }, [reference]);

  const openPreview = async () => {
    try {
      const res = await axios.get(
        `${API}/driver-export-versions/${state.data.driver_export_version_id}/preview`,
        { ...auth(), responseType: "blob" });
      const url = URL.createObjectURL(res.data);
      window.open(url, "_blank", "noopener,noreferrer");
    } catch (err) {
      // let the button silently fail — this is a verification screen
    }
  };

  return (
    <div className="min-h-screen bg-slate-50 text-slate-900" data-testid="export-verify-page">
      <div className="max-w-2xl mx-auto px-6 py-10">
        <div className="flex items-center gap-2 text-[11px] uppercase tracking-[0.15em] text-slate-500 mb-2">
          <ShieldCheck size={14} />
          <span>Driver Command Centre · Export Verification</span>
        </div>
        <h1 className="text-2xl font-bold text-slate-900 tracking-tight" data-testid="verify-title">
          Verify Export
        </h1>
        <div className="mt-1 font-mono text-sm text-slate-700" data-testid="verify-reference">{reference}</div>

        {state.loading && (
          <div className="mt-6 rounded-lg border border-slate-200 bg-white px-4 py-6 text-sm text-slate-500"
               data-testid="verify-loading">
            Verifying…
          </div>
        )}

        {state.error && (
          <div className="mt-6 rounded-lg border border-rose-200 bg-rose-50 px-4 py-6"
               data-testid="verify-error">
            <div className="inline-flex items-center gap-2 text-rose-800 font-medium mb-1">
              <XCircle size={16} /> Verification failed
            </div>
            <div className="text-sm text-rose-700">{state.error}</div>
            <div className="mt-2 text-xs text-rose-600">
              This reference is not linked to any known export in the Driver Command Centre.
              If you were expecting this to work, contact your Admin.
            </div>
          </div>
        )}

        {state.data && (
          <div className="mt-6 space-y-4">
            {/* Verdict card */}
            <div className={`rounded-lg border px-4 py-4 ${state.data.checksum_ok ? "border-emerald-200 bg-emerald-50" : "border-amber-200 bg-amber-50"}`}
                 data-testid="verify-verdict">
              <div className={`inline-flex items-center gap-2 font-medium mb-1 ${state.data.checksum_ok ? "text-emerald-800" : "text-amber-800"}`}>
                {state.data.checksum_ok
                  ? <><CheckCircle size={16} /> Checksum verified</>
                  : <><Warning size={16} /> Checksum could not be verified</>}
              </div>
              <div className="text-sm text-slate-700">
                {state.data.is_archived
                  ? <span data-testid="verify-archived">This export is <b>archived</b>. It is preserved as a historical record but is no longer the current version.</span>
                  : <span data-testid="verify-current">This export is the current version and remains valid.</span>}
              </div>
            </div>

            {/* Metadata */}
            <div className="rounded-lg border border-slate-200 bg-white divide-y divide-slate-100">
              <MetaRow label="Export type" value={
                <span className="inline-flex items-center gap-1.5">
                  {state.data.export_type === "Driver Start Sheet"
                    ? <FileArrowDown size={13} />
                    : <FilePdf size={13} />}
                  {state.data.export_type}
                </span>
              } testid="verify-export-type"/>
              <MetaRow label="Version" value={`v${state.data.version_number}`} testid="verify-version" />
              <MetaRow label="Generated" value={(state.data.generated_at || "").slice(0, 19).replace("T", " ")} testid="verify-generated-at" />
              <MetaRow label="Generated by" value={state.data.generated_by} testid="verify-generated-by" />
              {state.data.driver && (
                <>
                  <MetaRow label="Driver" value={state.data.driver.full_name} testid="verify-driver-name" />
                  <MetaRow label="Driver Code" value={state.data.driver.driver_code} testid="verify-driver-code" />
                </>
              )}
              <MetaRow label="SHA-256" value={<span className="font-mono text-[10.5px] break-all">{state.data.sha256}</span>} testid="verify-sha256" />
            </div>

            {state.data.can_open ? (
              <button onClick={openPreview}
                      data-testid="btn-verify-open"
                      className="w-full inline-flex items-center justify-center gap-1.5 rounded-md bg-slate-900 hover:bg-slate-800 text-white px-3 py-2 text-sm font-medium">
                <Eye size={14} /> Open export
              </button>
            ) : (
              <div className="rounded-lg border border-slate-200 bg-slate-50 px-4 py-3 text-sm text-slate-600"
                   data-testid="verify-locked">
                <div className="inline-flex items-center gap-2 font-medium text-slate-800 mb-1">
                  <Warning size={14} /> Restricted for your role
                </div>
                This export contains financial fields that require Manager or Admin access.
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}


function MetaRow({ label, value, testid }) {
  return (
    <div className="flex items-start gap-3 px-4 py-2.5">
      <div className="w-32 shrink-0 text-[10px] uppercase tracking-[0.15em] text-slate-500 pt-0.5">{label}</div>
      <div className="text-sm text-slate-900 min-w-0 flex-1" data-testid={testid}>{value || "—"}</div>
    </div>
  );
}
