// EB-04 Canonical Compliance page config, consumed by CompliancePage.jsx
// Each slug maps to one compliance record collection.
export const COMPLIANCE_TYPES = {
  "driver-licences": {
    slug: "driver-licences",
    title: "Driver Licences",
    heroLabel: "Canonical Compliance",
    description: "Primary driver licences — expiry, class and verification state.",
    api: "/driver-licences",
    entity: "driver",
    entityLabel: "Driver",
    columns: [
      { key: "entity", label: "Driver", type: "driver_lookup" },
      { key: "licence_number", label: "Licence #" },
      { key: "licence_class", label: "Class" },
      { key: "state", label: "State" },
      { key: "expiry_date", label: "Expiry" },
      { key: "is_primary", label: "Primary", type: "bool" },
      { key: "status", label: "Status", type: "status_badge" },
    ],
    createFields: [
      { key: "driver_id", label: "Driver", type: "driver_select", required: true },
      { key: "licence_number", label: "Licence Number", required: true },
      { key: "licence_class", label: "Class" },
      { key: "state", label: "State" },
      { key: "issue_date", label: "Issue Date", type: "date" },
      { key: "expiry_date", label: "Expiry Date", type: "date" },
      { key: "is_primary", label: "Primary Licence", type: "checkbox", default: true },
      { key: "notes", label: "Notes" },
    ],
  },
  "vehicle-registrations": {
    slug: "vehicle-registrations",
    title: "Vehicle Registration",
    heroLabel: "Canonical Compliance",
    description: "Current registration per vehicle. Historical records retained.",
    api: "/vehicle-registrations",
    entity: "vehicle",
    entityLabel: "Vehicle",
    columns: [
      { key: "entity", label: "Vehicle", type: "vehicle_lookup" },
      { key: "registration_number_snapshot", label: "Rego (snapshot)" },
      { key: "state", label: "State" },
      { key: "registration_class", label: "Class" },
      { key: "expiry_date", label: "Expiry" },
      { key: "is_current", label: "Current", type: "bool" },
      { key: "status", label: "Status", type: "status_badge" },
    ],
    createFields: [
      { key: "vehicle_id", label: "Vehicle", type: "vehicle_select", required: true },
      { key: "registration_number_snapshot", label: "Registration Number (snapshot)" },
      { key: "state", label: "State" },
      { key: "registration_class", label: "Class" },
      { key: "issue_date", label: "Issue Date", type: "date" },
      { key: "expiry_date", label: "Expiry Date", type: "date" },
      { key: "is_current", label: "Set as Current", type: "checkbox", default: true },
      { key: "notes", label: "Notes" },
    ],
  },
  "vehicle-insurance": {
    slug: "vehicle-insurance",
    title: "Vehicle Insurance",
    heroLabel: "Canonical Compliance",
    description: "Current insurance policies per vehicle. One current per cover type.",
    api: "/vehicle-insurance",
    entity: "vehicle",
    entityLabel: "Vehicle",
    columns: [
      { key: "entity", label: "Vehicle", type: "vehicle_lookup" },
      { key: "policy_number", label: "Policy #" },
      { key: "provider", label: "Provider" },
      { key: "cover_type", label: "Cover" },
      { key: "expiry_date", label: "Expiry" },
      { key: "is_current", label: "Current", type: "bool" },
      { key: "status", label: "Status", type: "status_badge" },
    ],
    createFields: [
      { key: "vehicle_id", label: "Vehicle", type: "vehicle_select", required: true },
      { key: "policy_number", label: "Policy Number", required: true },
      { key: "provider", label: "Provider" },
      { key: "cover_type", label: "Cover Type", type: "select",
        options: ["Comprehensive", "Third Party", "Fire & Theft", "Heavy Vehicle", "Other"] },
      { key: "effective_date", label: "Effective Date", type: "date" },
      { key: "expiry_date", label: "Expiry Date", type: "date" },
      { key: "is_current", label: "Set as Current", type: "checkbox", default: true },
      { key: "notes", label: "Notes" },
    ],
  },
  "vehicle-inspections": {
    slug: "vehicle-inspections",
    title: "Vehicle Inspections",
    heroLabel: "Canonical Compliance",
    description: "Roadworthy and scheduled inspections. Fails feed into vehicle compliance.",
    api: "/vehicle-inspections",
    entity: "vehicle",
    entityLabel: "Vehicle",
    columns: [
      { key: "entity", label: "Vehicle", type: "vehicle_lookup" },
      { key: "inspection_type", label: "Type" },
      { key: "inspection_date", label: "Date" },
      { key: "next_inspection_due", label: "Next Due" },
      { key: "result", label: "Result" },
      { key: "status", label: "Status", type: "status_badge" },
    ],
    createFields: [
      { key: "vehicle_id", label: "Vehicle", type: "vehicle_select", required: true },
      { key: "inspection_type", label: "Inspection Type", type: "select",
        options: ["Roadworthy", "Scheduled Inspection", "Pre-Start Inspection", "Annual Inspection", "Other"] },
      { key: "inspection_date", label: "Inspection Date", type: "date" },
      { key: "next_inspection_due", label: "Next Inspection Due", type: "date" },
      { key: "result", label: "Result", type: "select",
        options: ["Pass", "Pass with Observations", "Fail", "Pending"] },
      { key: "inspector_name", label: "Inspector" },
      { key: "odometer", label: "Odometer", type: "number" },
      { key: "notes", label: "Notes" },
    ],
  },
  "vehicle-defects": {
    slug: "vehicle-defects",
    title: "Vehicle Defects",
    heroLabel: "Canonical Compliance",
    description: "Defect register. Critical open defects block Vehicle Compliance.",
    api: "/vehicle-defects",
    entity: "vehicle",
    entityLabel: "Vehicle",
    columns: [
      { key: "entity", label: "Vehicle", type: "vehicle_lookup" },
      { key: "defect_number", label: "Defect #" },
      { key: "severity", label: "Severity", type: "severity_badge" },
      { key: "description", label: "Description" },
      { key: "reported_date", label: "Reported" },
      { key: "status", label: "Status", type: "defect_status_badge" },
    ],
    createFields: [
      { key: "vehicle_id", label: "Vehicle", type: "vehicle_select", required: true },
      { key: "defect_number", label: "Defect Number" },
      { key: "reported_date", label: "Reported Date", type: "date" },
      { key: "severity", label: "Severity", type: "select", options: ["Low", "Medium", "High", "Critical"] },
      { key: "description", label: "Description", required: true },
      { key: "status", label: "Status", type: "select",
        options: ["Open", "Under Review", "Repair Scheduled", "Rectified", "Closed"] },
      { key: "rectification_required", label: "Rectification Required", type: "checkbox", default: true },
      { key: "notes", label: "Notes" },
    ],
  },
  "vehicle-maintenance-tasks": {
    slug: "vehicle-maintenance-tasks",
    title: "Vehicle Maintenance",
    heroLabel: "Canonical Compliance",
    description: "Scheduled, in-progress and completed maintenance tasks.",
    api: "/vehicle-maintenance-tasks",
    entity: "vehicle",
    entityLabel: "Vehicle",
    columns: [
      { key: "entity", label: "Vehicle", type: "vehicle_lookup" },
      { key: "task_type", label: "Task" },
      { key: "scheduled_date", label: "Scheduled" },
      { key: "completed_date", label: "Completed" },
      { key: "provider", label: "Provider" },
      { key: "status", label: "Status", type: "maintenance_status_badge" },
    ],
    createFields: [
      { key: "vehicle_id", label: "Vehicle", type: "vehicle_select", required: true },
      { key: "task_type", label: "Task Type", required: true },
      { key: "description", label: "Description" },
      { key: "scheduled_date", label: "Scheduled Date", type: "date" },
      { key: "completed_date", label: "Completed Date", type: "date" },
      { key: "status", label: "Status", type: "select",
        options: ["Scheduled", "Due Soon", "Overdue", "In Progress", "Completed", "Cancelled"] },
      { key: "provider", label: "Provider" },
      { key: "cost", label: "Cost", type: "number" },
      { key: "notes", label: "Notes" },
    ],
  },
  "equipment-compliance": {
    slug: "equipment-compliance",
    title: "Equipment Compliance",
    heroLabel: "Canonical Compliance",
    description: "Compliance types per piece of equipment (cert, inspection, insurance).",
    api: "/equipment-compliance",
    entity: "equipment",
    entityLabel: "Equipment",
    columns: [
      { key: "entity", label: "Equipment", type: "equipment_lookup" },
      { key: "compliance_type", label: "Type" },
      { key: "reference_number", label: "Ref" },
      { key: "expiry_date", label: "Expiry" },
      { key: "is_current", label: "Current", type: "bool" },
      { key: "status", label: "Status", type: "status_badge" },
    ],
    createFields: [
      { key: "equipment_id", label: "Equipment", type: "equipment_select", required: true },
      { key: "compliance_type", label: "Compliance Type", type: "select",
        options: ["Registration", "Inspection", "Certification", "Insurance", "Maintenance", "Other"] },
      { key: "reference_number", label: "Reference Number" },
      { key: "effective_date", label: "Effective Date", type: "date" },
      { key: "expiry_date", label: "Expiry Date", type: "date" },
      { key: "is_current", label: "Set as Current", type: "checkbox", default: true },
      { key: "is_mandatory", label: "Mandatory", type: "checkbox", default: true },
      { key: "notes", label: "Notes" },
    ],
  },
};

export const COMPLIANCE_SLUGS = Object.keys(COMPLIANCE_TYPES);

// Status → tailwind classes for the canonical status badge
export const STATUS_STYLES = {
  Compliant: "bg-emerald-50 text-emerald-700 border-emerald-200",
  "Due Soon": "bg-amber-50 text-amber-700 border-amber-200",
  Expired: "bg-red-50 text-red-700 border-red-200",
  Missing: "bg-red-50 text-red-700 border-red-200",
  Incomplete: "bg-slate-100 text-slate-700 border-slate-200",
  "Under Review": "bg-blue-50 text-blue-700 border-blue-200",
  "Not Applicable": "bg-slate-50 text-slate-500 border-slate-200",
  Archived: "bg-slate-100 text-slate-500 border-slate-200",
};

export const STATUS_DOT = {
  Compliant: "bg-emerald-500",
  "Due Soon": "bg-amber-500",
  Expired: "bg-red-500",
  Missing: "bg-red-500",
  Incomplete: "bg-slate-400",
  "Under Review": "bg-blue-500",
  "Not Applicable": "bg-slate-300",
  Archived: "bg-slate-400",
};
