// EB-03 Relationship & Assignment config used by RelationshipPage.jsx
export const RELATIONSHIPS = {
  "driver-owner": {
    slug: "driver-owner",
    title: "Driver – Owner Relationships",
    heroLabel: "Relationships & Assignments",
    description: "Ownership context per driver — company, contractor, self-owned or relief.",
    api: "/driver-owner-relationships",
    activeField: "is_current",
    activeLabel: "Current",
    activeApiKey: "is_current",
    supportsReassign: false,
    lookups: ["driver", "owner"],
    columns: [
      { key: "driver", label: "Driver", type: "driver_lookup" },
      { key: "owner", label: "Owner", type: "owner_lookup" },
      { key: "relationship_type", label: "Type" },
      { key: "start_date", label: "Start" },
      { key: "end_date", label: "End" },
      { key: "is_current", label: "Status", type: "current_badge" },
    ],
    createFields: [
      { key: "driver_id", label: "Driver", type: "driver_select", required: true },
      { key: "owner_id", label: "Owner", type: "owner_select", required: true },
      {
        key: "relationship_type",
        label: "Relationship Type",
        type: "select",
        options: ["Self Owned", "Company Driver", "Contractor Driver", "Relief Driver", "Other"],
      },
      { key: "is_current", label: "Set as Current", type: "checkbox", default: true },
      { key: "start_date", label: "Start Date", type: "date" },
      { key: "notes", label: "Notes" },
    ],
  },

  "driver-vehicle": {
    slug: "driver-vehicle",
    title: "Driver – Vehicle Assignments",
    heroLabel: "Relationships & Assignments",
    description: "Which driver is currently allocated to each vehicle. History retained.",
    api: "/driver-vehicle-assignments",
    activeField: "is_active",
    activeLabel: "Active",
    activeApiKey: "is_active",
    supportsReassign: true,
    reassignApi: "/driver-vehicle-assignments/reassign",
    reassignFields: [
      { key: "driver_id", label: "New Driver", type: "driver_select", required: true },
      { key: "vehicle_id", label: "Vehicle", type: "vehicle_select", required: true },
      { key: "start_date", label: "Start Date", type: "date" },
      { key: "notes", label: "Notes" },
    ],
    lookups: ["driver", "vehicle"],
    columns: [
      { key: "driver", label: "Driver", type: "driver_lookup" },
      { key: "vehicle", label: "Vehicle", type: "vehicle_lookup" },
      { key: "is_primary", label: "Primary", type: "bool" },
      { key: "display_on_dispatch", label: "On Dispatch", type: "bool" },
      { key: "start_date", label: "Start" },
      { key: "end_date", label: "End" },
      { key: "is_active", label: "Status", type: "active_badge" },
    ],
    createFields: [
      { key: "driver_id", label: "Driver", type: "driver_select", required: true },
      { key: "vehicle_id", label: "Vehicle", type: "vehicle_select", required: true },
      { key: "is_primary", label: "Primary", type: "checkbox", default: true },
      { key: "display_on_dispatch", label: "Show on Dispatch", type: "checkbox", default: true },
      { key: "dispatch_number_snapshot", label: "Dispatch Number (history)" },
      { key: "start_date", label: "Start Date", type: "date" },
      { key: "notes", label: "Notes" },
    ],
  },

  "driver-equipment": {
    slug: "driver-equipment",
    title: "Driver – Equipment Assignments",
    heroLabel: "Relationships & Assignments",
    description: "Trays, trailers and other equipment currently allocated to drivers.",
    api: "/driver-equipment-assignments",
    activeField: "is_active",
    activeLabel: "Active",
    activeApiKey: "is_active",
    supportsReassign: true,
    reassignApi: "/driver-equipment-assignments/reassign",
    reassignFields: [
      { key: "driver_id", label: "New Driver", type: "driver_select", required: true },
      { key: "equipment_id", label: "Equipment", type: "equipment_select", required: true },
      { key: "start_date", label: "Start Date", type: "date" },
      { key: "notes", label: "Notes" },
    ],
    lookups: ["driver", "equipment"],
    columns: [
      { key: "driver", label: "Driver", type: "driver_lookup" },
      { key: "equipment", label: "Equipment", type: "equipment_lookup" },
      { key: "start_date", label: "Start" },
      { key: "end_date", label: "End" },
      { key: "is_active", label: "Status", type: "active_badge" },
    ],
    createFields: [
      { key: "driver_id", label: "Driver", type: "driver_select", required: true },
      { key: "equipment_id", label: "Equipment", type: "equipment_select", required: true },
      { key: "start_date", label: "Start Date", type: "date" },
      { key: "notes", label: "Notes" },
    ],
  },
};

export const RELATIONSHIP_SLUGS = ["driver-owner", "driver-vehicle", "driver-equipment"];
